compute_environment: LOCAL_MACHINE
deepspeed_config:
  deepspeed_multinode_launcher: standard
  zero3_init_flag: true
  zero3_save_16bit_model: true
  zero_stage: 3
distributed_type: DEEPSPEED
downcast_bf16: 'no'
mixed_precision: bf16
num_machines: 1
num_processes: 2
machine_rank: 0
main_training_function: main
use_cpu: false
