compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  deepspeed_multinode_launcher: standard
  offload_optimizer_device: none
  offload_param_device: none
  zero3_init_flag: true
  zero3_save_16bit_model: true
  zero_stage: 3
distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false

# zero_optimization:
#   stage: 3
#   offload_optimizer: {
#     device: nvme,
#     pin_memory: true
#   }
#   offload_param: {
#     device: nvme,
#     pin_memory: true
#   }
#   overlap_comm: true
#   contiguous_gradients: true
#   reduce_bucket_size: 5e8
#   stage3_prefetch_bucket_size: 5e8
#   stage3_param_persistence_threshold: 1e6
#   stage3_max_live_parameters: 1e9
#   stage3_max_reuse_distance: 1e7
#   stage3_gather_fp16_weights_on_model_save: true

# fp16:
#   enabled: true

# train_micro_batch_size_per_gpu: 2
# gradient_accumulation_steps: 4
# steps_per_print: 2000
# wall_clock_breakdown: false
